apiVersion: v2
name: sd-customer-profile
description: "BIAN Service Domain: Customer Profile (Maintain pattern, Sales and Service)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - maintain
annotations:
  bian/business-area: "Sales and Service"
  bian/business-domain: "Customer Management"
  bian/asset-type: "Customer Profile"
  bian/control-record: "Customer Profile Maintenance Agreement"
